name: Budowanie aplikacji (PyInstaller)

on:
  push:
    branches: [ "master" ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Budowanie na systemie ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            sep: ";"
            flags: "--windowed"
            artifact_name: "Wycena-Windows"
          - os: macos-latest
            sep: ":"
            flags: "--windowed"
            artifact_name: "Wycena-Mac"
          - os: ubuntu-latest
            sep: ":"
            flags: ""
            artifact_name: "Wycena-Linux"

    steps:
    - name: Klonowanie repozytorium
      uses: actions/checkout@v4

    - name: Konfiguracja Pythona 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip' 

    - name: Instalacja zależności
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Kompilacja PyInstaller
      run: |
        pyinstaller --name "WycenaNieruchomosci" ${{ matrix.flags }} --add-data "app/static${{ matrix.sep }}static" --add-data "data${{ matrix.sep }}data" --add-data "model${{ matrix.sep }}model" app/api.py

    - name: Wrzucenie gotowej paczki (Artifact)
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/WycenaNieruchomosci/
        retention-days: 7 
